[package]
name = "ground-covered"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
curl = "0.4.44"
redis = { version = "0.23.0", features = ["json"] }
serde = "1.0.162"
serde_derive = "1.0.162"
serde_json = "1.0.96"
toml = "0.7.3"
